ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: |
      ./install.sh
    command: |
      sudo apt-get install entr
      ls *.csv *.json *.sh | entr -r ./start.sh

vscode:
  extensions:
    - ssvelte.svelte-vscode
    - bradlc.vscode-tailwindcss@0.6.11
    - https://example.com/abc/releases/extension-0.26.0.vsix